"""
Database of sources for absurd correlations.
This file is automatically generated, do not modify directly.
"""

SOURCES = {
    # ALIMENTATION
    "cafes_machine": {
        "name": "INRA - Number of coffees drunk while waiting for meeting to end",
        "url": "https://www.inrae.fr/etudes/2024/consommation-reunions",
        "category": "alimentation"
    },

    "meeting_cakes": {
        "name": "Nielsen - Correlation between cake presence and meeting duration",
        "url": "https://www.nielsen.com/fr/etudes/2024/productivite-collations",
        "category": "alimentation"
    },

    # ECONOMIE
    "world_bank_pib_2063": {
        "name": "world_bank - GDP (2022)",
        "url": "https://data.worldbank.org/indicator/NY.GDP.MKTP.CD",
        "category": "economie",
        "metadata": {
            "indicator": "GDP",
            "year": "2022",
            "value": 2796302210398.84,
            "country": "France"
        }
    },

    "world_bank_pib_2357": {
        "name": "world_bank - GDP (2020)",
        "url": "https://data.worldbank.org/indicator/NY.GDP.MKTP.CD",
        "category": "economie",
        "metadata": {
            "indicator": "GDP",
            "year": "2020",
            "value": 2647926055110.05,
            "country": "France"
        }
    },

    # EDUCATION
    "world_bank_education_spending_1729": {
        "name": "world_bank - Education spending (2011)",
        "url": "https://data.worldbank.org/indicator/SE.XPD.TOTL.GD.ZS",
        "category": "education",
        "metadata": {
            "indicator": "Education spending",
            "year": "2011",
            "value": 5.48011541366577,
            "country": "France"
        }
    }
} 